/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProjectDto,
  CreateProjectResponseDto,
  DeleteProjectResponseDto,
  ProjectsControllerGetProjectsByUserParams,
  ProjectsControllerGetProjectsParams,
  ProjectsListResponseDto
} from '../../schemas';

import { axiosInstance } from '../../instance/axiosInstance';
import type { ErrorType } from '../../instance/axiosInstance';




export const projectsControllerGetProjects = (
    params?: ProjectsControllerGetProjectsParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProjectsListResponseDto>(
      {url: `/projects`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getProjectsControllerGetProjectsQueryKey = (params?: ProjectsControllerGetProjectsParams,) => {
    return [`/projects`, ...(params ? [params]: [])] as const;
    }

    
export const getProjectsControllerGetProjectsQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError = ErrorType<unknown>>(params?: ProjectsControllerGetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerGetProjectsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerGetProjects>>> = ({ signal }) => projectsControllerGetProjects(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerGetProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerGetProjects>>>
export type ProjectsControllerGetProjectsQueryError = ErrorType<unknown>


export function useProjectsControllerGetProjects<TData = Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError = ErrorType<unknown>>(
 params: undefined |  ProjectsControllerGetProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerGetProjects>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerGetProjects>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerGetProjects<TData = Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError = ErrorType<unknown>>(
 params?: ProjectsControllerGetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerGetProjects>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerGetProjects>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerGetProjects<TData = Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError = ErrorType<unknown>>(
 params?: ProjectsControllerGetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProjectsControllerGetProjects<TData = Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError = ErrorType<unknown>>(
 params?: ProjectsControllerGetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjects>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerGetProjectsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const projectsControllerCreateProject = (
    createProjectDto: CreateProjectDto,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<CreateProjectResponseDto>(
      {url: `/projects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProjectDto, signal
    },
      );
    }
  


export const getProjectsControllerCreateProjectMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerCreateProject>>, TError,{data: CreateProjectDto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerCreateProject>>, TError,{data: CreateProjectDto}, TContext> => {

const mutationKey = ['projectsControllerCreateProject'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerCreateProject>>, {data: CreateProjectDto}> = (props) => {
          const {data} = props ?? {};

          return  projectsControllerCreateProject(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerCreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerCreateProject>>>
    export type ProjectsControllerCreateProjectMutationBody = CreateProjectDto
    export type ProjectsControllerCreateProjectMutationError = ErrorType<unknown>

    export const useProjectsControllerCreateProject = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerCreateProject>>, TError,{data: CreateProjectDto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerCreateProject>>,
        TError,
        {data: CreateProjectDto},
        TContext
      > => {

      const mutationOptions = getProjectsControllerCreateProjectMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const projectsControllerGetProjectsByUser = (
    userId: string,
    params?: ProjectsControllerGetProjectsByUserParams,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<ProjectsListResponseDto>(
      {url: `/projects/user/${userId}`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getProjectsControllerGetProjectsByUserQueryKey = (userId?: string,
    params?: ProjectsControllerGetProjectsByUserParams,) => {
    return [`/projects/user/${userId}`, ...(params ? [params]: [])] as const;
    }

    
export const getProjectsControllerGetProjectsByUserQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError = ErrorType<unknown>>(userId: string,
    params?: ProjectsControllerGetProjectsByUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerGetProjectsByUserQueryKey(userId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>> = ({ signal }) => projectsControllerGetProjectsByUser(userId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerGetProjectsByUserQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>>
export type ProjectsControllerGetProjectsByUserQueryError = ErrorType<unknown>


export function useProjectsControllerGetProjectsByUser<TData = Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError = ErrorType<unknown>>(
 userId: string,
    params: undefined |  ProjectsControllerGetProjectsByUserParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerGetProjectsByUser<TData = Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError = ErrorType<unknown>>(
 userId: string,
    params?: ProjectsControllerGetProjectsByUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerGetProjectsByUser<TData = Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError = ErrorType<unknown>>(
 userId: string,
    params?: ProjectsControllerGetProjectsByUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProjectsControllerGetProjectsByUser<TData = Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError = ErrorType<unknown>>(
 userId: string,
    params?: ProjectsControllerGetProjectsByUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerGetProjectsByUser>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerGetProjectsByUserQueryOptions(userId,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const projectsControllerDeleteProject = (
    id: string,
 ) => {
      
      
      return axiosInstance<DeleteProjectResponseDto>(
      {url: `/projects/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getProjectsControllerDeleteProjectMutationOptions = <TError = ErrorType<null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerDeleteProject>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerDeleteProject>>, TError,{id: string}, TContext> => {

const mutationKey = ['projectsControllerDeleteProject'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerDeleteProject>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  projectsControllerDeleteProject(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerDeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerDeleteProject>>>
    
    export type ProjectsControllerDeleteProjectMutationError = ErrorType<null>

    export const useProjectsControllerDeleteProject = <TError = ErrorType<null>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerDeleteProject>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerDeleteProject>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getProjectsControllerDeleteProjectMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    