/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */

export interface CreateProjectResponseDto {
  /** Уникальный идентификатор созданного проекта */
  id: string;
  /** Название проекта */
  name: string;
  /** Описание проекта */
  description: string;
  /** Дата создания проекта */
  createdAt: string;
  /** Дата последнего обновления проекта */
  updatedAt: string;
  /** Статус верификации проекта */
  isVerified: boolean;
  /** Статус блокировки проекта */
  isBlocked: boolean;
}
