/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */

export interface DeleteProjectResponseDto {
  /** Сообщение об успешном удалении */
  message: string;
}
