/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDto } from './userResponseDto';

export interface ProjectResponseDto {
  /** Уникальный идентификатор проекта */
  id: string;
  /** Название проекта */
  name: string;
  /** Описание проекта */
  description: string;
  /** Дата создания проекта */
  createdAt: string;
  /** Дата последнего обновления проекта */
  updatedAt: string;
  /** Статус верификации проекта */
  isVerified: boolean;
  /** Статус блокировки проекта */
  isBlocked: boolean;
  /** Информация о пользователе */
  user: UserResponseDto;
}
