/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */

export type ProjectsControllerGetProjectsByUserParams = {
/**
 * Номер страницы для пагинации
 * @minimum 1
 */
page?: number;
/**
 * Количество проектов на странице
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Поисковый запрос для фильтрации проектов по названию или описанию
 */
search?: string;
/**
 * Фильтр по статусу верификации проекта
 */
isVerified?: boolean;
/**
 * Фильтр по статусу блокировки проекта
 */
isBlocked?: boolean;
};
