/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */

export interface UserResponseDto {
  /** Уникальный идентификатор пользователя */
  id: string;
  /** Имя пользователя */
  firstName: string;
  /** Фамилия пользователя */
  lastName: string;
}
