/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */

export interface CreateProjectDto {
  /** Название проекта */
  name: string;
  /** Описание проекта */
  description: string;
  /** Белый список URL для проекта */
  whiteUrls?: string[];
  /** Пространства имен для проекта */
  nameSpaces?: string[];
}
