/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** Email */
  email: string;
  /** Password */
  password: string;
}
