/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /** Organization name */
  organizationName: string;
  /** Last name of the user */
  lastName: string;
  /** First name of the user */
  firstName: string;
  /** Email of the user */
  email: string;
  /** Password of the user */
  password: string;
}
