/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { axiosInstance } from '../../instance/axiosInstance';
import type { ErrorType } from '../../instance/axiosInstance';




export const userControllerGetProfile = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<null>(
      {url: `/profile/profile`, method: 'GET', signal
    },
      );
    }
  

export const getUserControllerGetProfileQueryKey = () => {
    return [`/profile/profile`] as const;
    }

    
export const getUserControllerGetProfileQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetProfile>>> = ({ signal }) => userControllerGetProfile(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserControllerGetProfileQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetProfile>>>
export type UserControllerGetProfileQueryError = ErrorType<unknown>


export function useUserControllerGetProfile<TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetProfile<TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserControllerGetProfile<TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserControllerGetProfile<TData = Awaited<ReturnType<typeof userControllerGetProfile>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserControllerGetProfileQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const userControllerUpdateProfile = (
    id: string,
 ) => {
      
      
      return axiosInstance<null>(
      {url: `/profile/${id}`, method: 'PUT'
    },
      );
    }
  


export const getUserControllerUpdateProfileMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateProfile>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateProfile>>, TError,{id: string}, TContext> => {

const mutationKey = ['userControllerUpdateProfile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdateProfile>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  userControllerUpdateProfile(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerUpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateProfile>>>
    
    export type UserControllerUpdateProfileMutationError = ErrorType<unknown>

    export const useUserControllerUpdateProfile = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateProfile>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerUpdateProfile>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getUserControllerUpdateProfileMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const userControllerUpdateUserPassword = (
    id: string,
 ) => {
      
      
      return axiosInstance<null>(
      {url: `/profile/update-password/${id}`, method: 'PUT'
    },
      );
    }
  


export const getUserControllerUpdateUserPasswordMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateUserPassword>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateUserPassword>>, TError,{id: string}, TContext> => {

const mutationKey = ['userControllerUpdateUserPassword'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdateUserPassword>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  userControllerUpdateUserPassword(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerUpdateUserPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateUserPassword>>>
    
    export type UserControllerUpdateUserPasswordMutationError = ErrorType<unknown>

    export const useUserControllerUpdateUserPassword = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateUserPassword>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userControllerUpdateUserPassword>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getUserControllerUpdateUserPasswordMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    