/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Translation API
 * The translation API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Translations
} from '../../schemas';

import { axiosInstance } from '../../instance/axiosInstance';
import type { ErrorType } from '../../instance/axiosInstance';




export const translationsControllerGetTranslationsAll = (
    
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<null>(
      {url: `/translations`, method: 'GET', signal
    },
      );
    }
  

export const getTranslationsControllerGetTranslationsAllQueryKey = () => {
    return [`/translations`] as const;
    }

    
export const getTranslationsControllerGetTranslationsAllQueryOptions = <TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTranslationsControllerGetTranslationsAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>> = ({ signal }) => translationsControllerGetTranslationsAll(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TranslationsControllerGetTranslationsAllQueryResult = NonNullable<Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>>
export type TranslationsControllerGetTranslationsAllQueryError = ErrorType<unknown>


export function useTranslationsControllerGetTranslationsAll<TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>,
          TError,
          Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTranslationsControllerGetTranslationsAll<TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>,
          TError,
          Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTranslationsControllerGetTranslationsAll<TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTranslationsControllerGetTranslationsAll<TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsAll>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTranslationsControllerGetTranslationsAllQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const translationsControllerCreateTranslation = (
    translations: Translations,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<null>(
      {url: `/translations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: translations, signal
    },
      );
    }
  


export const getTranslationsControllerCreateTranslationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof translationsControllerCreateTranslation>>, TError,{data: Translations}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof translationsControllerCreateTranslation>>, TError,{data: Translations}, TContext> => {

const mutationKey = ['translationsControllerCreateTranslation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof translationsControllerCreateTranslation>>, {data: Translations}> = (props) => {
          const {data} = props ?? {};

          return  translationsControllerCreateTranslation(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TranslationsControllerCreateTranslationMutationResult = NonNullable<Awaited<ReturnType<typeof translationsControllerCreateTranslation>>>
    export type TranslationsControllerCreateTranslationMutationBody = Translations
    export type TranslationsControllerCreateTranslationMutationError = ErrorType<unknown>

    export const useTranslationsControllerCreateTranslation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof translationsControllerCreateTranslation>>, TError,{data: Translations}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof translationsControllerCreateTranslation>>,
        TError,
        {data: Translations},
        TContext
      > => {

      const mutationOptions = getTranslationsControllerCreateTranslationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const translationsControllerGetTranslationsByProjectId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return axiosInstance<null>(
      {url: `/translations/${id}`, method: 'GET', signal
    },
      );
    }
  

export const getTranslationsControllerGetTranslationsByProjectIdQueryKey = (id?: string,) => {
    return [`/translations/${id}`] as const;
    }

    
export const getTranslationsControllerGetTranslationsByProjectIdQueryOptions = <TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTranslationsControllerGetTranslationsByProjectIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>> = ({ signal }) => translationsControllerGetTranslationsByProjectId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TranslationsControllerGetTranslationsByProjectIdQueryResult = NonNullable<Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>>
export type TranslationsControllerGetTranslationsByProjectIdQueryError = ErrorType<unknown>


export function useTranslationsControllerGetTranslationsByProjectId<TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>,
          TError,
          Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTranslationsControllerGetTranslationsByProjectId<TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>,
          TError,
          Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTranslationsControllerGetTranslationsByProjectId<TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTranslationsControllerGetTranslationsByProjectId<TData = Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof translationsControllerGetTranslationsByProjectId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTranslationsControllerGetTranslationsByProjectIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const translationsControllerUpdateTranslation = (
    id: string,
    translations: Translations,
 ) => {
      
      
      return axiosInstance<null>(
      {url: `/translations/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: translations
    },
      );
    }
  


export const getTranslationsControllerUpdateTranslationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof translationsControllerUpdateTranslation>>, TError,{id: string;data: Translations}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof translationsControllerUpdateTranslation>>, TError,{id: string;data: Translations}, TContext> => {

const mutationKey = ['translationsControllerUpdateTranslation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof translationsControllerUpdateTranslation>>, {id: string;data: Translations}> = (props) => {
          const {id,data} = props ?? {};

          return  translationsControllerUpdateTranslation(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TranslationsControllerUpdateTranslationMutationResult = NonNullable<Awaited<ReturnType<typeof translationsControllerUpdateTranslation>>>
    export type TranslationsControllerUpdateTranslationMutationBody = Translations
    export type TranslationsControllerUpdateTranslationMutationError = ErrorType<unknown>

    export const useTranslationsControllerUpdateTranslation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof translationsControllerUpdateTranslation>>, TError,{id: string;data: Translations}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof translationsControllerUpdateTranslation>>,
        TError,
        {id: string;data: Translations},
        TContext
      > => {

      const mutationOptions = getTranslationsControllerUpdateTranslationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const translationsControllerDeleteTranslation = (
    id: string,
 ) => {
      
      
      return axiosInstance<null>(
      {url: `/translations/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getTranslationsControllerDeleteTranslationMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof translationsControllerDeleteTranslation>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof translationsControllerDeleteTranslation>>, TError,{id: string}, TContext> => {

const mutationKey = ['translationsControllerDeleteTranslation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof translationsControllerDeleteTranslation>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  translationsControllerDeleteTranslation(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TranslationsControllerDeleteTranslationMutationResult = NonNullable<Awaited<ReturnType<typeof translationsControllerDeleteTranslation>>>
    
    export type TranslationsControllerDeleteTranslationMutationError = ErrorType<unknown>

    export const useTranslationsControllerDeleteTranslation = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof translationsControllerDeleteTranslation>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof translationsControllerDeleteTranslation>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getTranslationsControllerDeleteTranslationMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    export const translationsControllerChangeVerified = (
    id: string,
    boolean: boolean,
 ) => {
      
      
      return axiosInstance<null>(
      {url: `/translations/${id}/verified`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: boolean
    },
      );
    }
  


export const getTranslationsControllerChangeVerifiedMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof translationsControllerChangeVerified>>, TError,{id: string;data: boolean}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof translationsControllerChangeVerified>>, TError,{id: string;data: boolean}, TContext> => {

const mutationKey = ['translationsControllerChangeVerified'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof translationsControllerChangeVerified>>, {id: string;data: boolean}> = (props) => {
          const {id,data} = props ?? {};

          return  translationsControllerChangeVerified(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type TranslationsControllerChangeVerifiedMutationResult = NonNullable<Awaited<ReturnType<typeof translationsControllerChangeVerified>>>
    export type TranslationsControllerChangeVerifiedMutationBody = boolean
    export type TranslationsControllerChangeVerifiedMutationError = ErrorType<unknown>

    export const useTranslationsControllerChangeVerified = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof translationsControllerChangeVerified>>, TError,{id: string;data: boolean}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof translationsControllerChangeVerified>>,
        TError,
        {id: string;data: boolean},
        TContext
      > => {

      const mutationOptions = getTranslationsControllerChangeVerifiedMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    